language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install: pip install --use-mirrors .
before_script: 
  - pip install -r tests/requirements.txt --use-mirrors
script:  coverage run --source=pyrecord setup.py test
after_success:
  - coveralls
