language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install: pip install --requirement dev-requirements.txt
script:
  - coverage run --source=pyrecord setup.py test
  - pep8
  - python setup.py build_sphinx
  - python setup.py sdist
after_success:
  - coveralls
