language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install: pip install --requirement dev-requirements.txt
script: ./verify-codebase.sh
after_success:
  - coveralls
